name: MLflow CI Training

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # ✅ INSTALL CONDA
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.10
          activate-environment: base

      # ✅ INSTALL MLFLOW
      - name: Install dependencies
        run: |
          pip install mlflow

      # ✅ RUN MLFLOW PROJECT
      - name: Run MLflow Project
        run: |
          mlflow run MLProject