name: MLflow CI Training

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # ✅ INSTALL MINICONDA STABLE
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          auto-activate-base: true
          activate-environment: base
          python-version: 3.10

      # ✅ IMPORTANT → reload shell conda
      - name: Init Conda
        run: |
          conda init bash
          source ~/.bashrc
          conda info

      # ✅ Install MLflow
      - name: Install MLflow
        run: |
          pip install mlflow

      # ✅ Run MLflow Project
      - name: Run Training
        run: |
          mlflow run MLProject